# Generated by Django 4.1 on 2022-08-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('credential_id', models.TextField(primary_key=True, serialize=False)),
                ('base_url', models.TextField()),
                ('access_transcript_from', models.TextField()),
                ('user_email_address', models.EmailField(max_length=254)),
                ('user_access_code', models.TextField()),
                ('part1_name1', models.TextField()),
                ('part1_name2', models.TextField()),
                ('part1_name3', models.TextField()),
                ('part1_until_date', models.TextField()),
                ('part1_university_website', models.TextField()),
                ('school_logo_path', models.TextField()),
                ('pdf_file_path', models.TextField()),
                ('email_send_interval', models.TextField()),
            ],
        ),
    ]
