# Generated by Django 4.1 on 2022-08-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='left_logo_path',
        ),
        migrations.RemoveField(
            model_name='credential',
            name='right_logo_path',
        ),
        migrations.AddField(
            model_name='credential',
            name='part1_name1',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credential',
            name='part1_name2',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credential',
            name='part1_name3',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credential',
            name='part1_until_date',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credential',
            name='school_logo_path',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
